framework:
    default_locale: 'es'
    translator:
        fallbacks: ['es']

#framework:
    #default_locale: '%locale%'
    #translator:
     #   default_path: '%kernel.project_dir%/translations'
      #  fallbacks:
       #     - '%locale%'
